"""
Configuration file for Render deployment.
This file specifies build and run commands for the CV-to-Job Matching System.
"""

[build]
builder = "python"
buildCommand = "chmod +x build.sh && ./build.sh"

[web]
command = "gunicorn -c gunicorn.conf.py wsgi:app"
port = 10000
